"""create resources table

Revision ID: bffc0973ab70
Revises: 630c5a76ee4a
Create Date: 2025-12-18 14:13:37.725366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bffc0973ab70'
down_revision: Union[str, Sequence[str], None] = '630c5a76ee4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('room', 'equipment', 'vehicle', name='resource_type'), nullable=False),
    sa.Column('capacity_max', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('features', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('site', sa.String(length=120), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'maintenance', 'out_of_service', name='resource_status'), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('hourly_rate_internal', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'site', name='uq_resources_name_site')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
